<img src="pp.png" align ="center" width="900" height="600" /><br>
<h1 align ="center" style = "color:blue"> Numpy </h1>

# Introduction à NumPy

In [1]:
import numpy as np

## Variables prédéfinies

In [2]:
np.pi
3.141592653589793

3.141592653589793

## Tableaux - numpy.array()

In [3]:
a = np.array([1, 2, 3, 4])

In [7]:
a


array([1, 2, 3, 4])

In [8]:
type(a)

numpy.ndarray

## Tableau 2D

In [9]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [10]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
type(b)

numpy.ndarray

## Accès aux éléments d’un tableau 2D

In [13]:
b[0,1]

2

In [14]:
b[1,2]

6

## La fonction numpy.arange()

In [22]:
m = np.arange(3, 20, 2)
m

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [23]:
np.arange(0, 11*np.pi, np.pi)

array([ 0.        ,  3.14159265,  6.28318531,  9.42477796, 12.56637061,
       15.70796327, 18.84955592, 21.99114858, 25.13274123, 28.27433388,
       31.41592654])

## La fonction numpy.linspace()

In [24]:
np.linspace(3, 9, 10)

array([3.        , 3.66666667, 4.33333333, 5.        , 5.66666667,
       6.33333333, 7.        , 7.66666667, 8.33333333, 9.        ])

## Action d’une fonction mathématique sur un tableau

In [26]:
x = np.linspace(-np.pi/2, np.pi/2, 3)
x

array([-1.57079633,  0.        ,  1.57079633])

In [27]:
y = np.sin(x)
y

array([-1.,  0.,  1.])

## La fonction numpy.size()

In [28]:
a = np.array([2,5,6,8])
np.size(a)

4

In [29]:
b = np.array([[1, 2, 3],
                  [4, 5, 6]])
np.size(b)

6

## La fonction numpy.shape()

In [32]:
a = np.array([2,5,6,8])
np.shape(a)

(4,)

In [33]:
b = np.array([[1, 2, 3],
                  [4, 5, 6]])
np.shape(b)

(2, 3)

## Produit terme à terme

In [34]:
a = np.array([[1, 2, 3],
                  [4, 5, 6]])
b = np.array([[2, 1, 3],
                  [3, 2, 1]])
a*b

array([[ 2,  2,  9],
       [12, 10,  6]])